net.Receive("Gmod.Workshop.Death_Report", function()
	local DermaFrame1 = vgui.Create("DFrame")
	DermaFrame1:SetSize(300, 125)
	DermaFrame1:Center()
	DermaFrame1:SetTitle("Rapport de mort")
	DermaFrame1:SetDraggable(false)
	DermaFrame1:ShowCloseButton(false)
	DermaFrame1:SetBackgroundBlur(true)
	DermaFrame1:MakePopup()

	local DermaFrame2 = vgui.Create("DFrame")
	DermaFrame2:SetSize(300, 130)
	DermaFrame2:Center()
	DermaFrame2:SetTitle("Signalement")
	DermaFrame2:SetVisible(false)
	DermaFrame2:SetDraggable(false)
	DermaFrame2:SetBackgroundBlur(true)
	DermaFrame2:MakePopup()

	local DLabel1 = vgui.Create("DLabel", DermaFrame1)
	DLabel1:SetPos(95, 30)
	DLabel1:SetColor(Color(255, 255, 255, 255))
	DLabel1:SetText("Vous êtes mort " .. LocalPlayer():Nick() .. " !")
	DLabel1:SizeToContents()

	local DLabel2 = vgui.Create("DLabel", DermaFrame1)
	DLabel2:SetText("Avez-vous été tué de façon non roleplay ?")
	DLabel2:SetColor(Color(255, 255, 255, 255))
	DLabel2:SetPos(5, 50)
	DLabel2:SizeToContents()

	local DLabel3 = vgui.Create("DLabel", DermaFrame1)
	DLabel3:SetText("Note: Un faux rapport sera sanctionné !")
	DLabel3:SetPos(80, 85)
	DLabel3:SetColor(Color(255, 255, 255, 255))
	DLabel3:SizeToContents()

	local DButton1 = vgui.Create("DButton", DermaFrame1)
	DButton1:SetPos(5, 70)
	DButton1:SetText("Oui")
	DButton1:SetIcon("icon16/tick.png")
	DButton1.DoClick = function()
		DermaFrame1:Remove()
		DermaFrame2:SetVisible(true)
	end

	local DButton2 = vgui.Create("DButton", DermaFrame1)
	DButton2:SetPos(5, 95)
	DButton2:SetText("Non")
	DButton2:SetIcon("icon16/cross.png")
	DButton2.DoClick = function()
		DermaFrame1:Remove()
	end

	local DLabel4 = vgui.Create("DLabel", DermaFrame2)
	DLabel4:SetPos(10, 35)
	DLabel4:SetColor(Color(255, 255, 255, 255))
	DLabel4:SetText("Écrivez ici ce qu'il s'est passé de manière rapide.\nExemple : Julie m'a tué volontairement avec des props.")
	DLabel4:SizeToContents()

	local DTextEntry1 = vgui.Create("DTextEntry", DermaFrame2)
	DTextEntry1:SetPos(7.5, 70)
	DTextEntry1:SetWide(285)
	DTextEntry1:SetTall(20)

	local DButton3 = vgui.Create("DButton", DermaFrame2)
	DButton3:SetSize(200, 25)
	DButton3:SetPos(55, 97.5)
	DButton3:SetText("Envoyer le rapport")
	DButton3:SetIcon("icon16/report_go.png")
	DButton3.DoClick = function()
		RunConsoleCommand("say", "/// " .. DTextEntry1:GetValue())
		DermaFrame2:Remove()
	end
end)